### ISSUE TITLE
Syntax highlighting for commit in search

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#20]
SM 1063

The keyword `commit:` and the hash itself should be highlighted to give user feedback about correct spelling.

Example _Sublime Merge Search.sublime-syntax_

```
%YAML 1.2
---
scope: source.sublime-merge.search
contexts:
  main:
    - match: '"'
      scope: punctuation.definition.string.begin.search
      push: double_quoted_string

    - match: '\b(and|or|not)\b'
      scope: keyword.operator.logical.search

    - match: '\b(author:|path:|file:|line:|from:|min-parents:|max-parents:|commit:)'
      scope: keyword.search

    - match: '\b-?[0-9]+\b'
      scope: constant.numeric.integer.search

    - match: '\b[a-f0-9]{2,21}\b'
      scope: constant.numeric.hex.search

    - match: '\('
      scope: punctuation.section.brackets.begin.search
    - match: '\)'
      scope: punctuation.section.brackets.end.search

  double_quoted_string:
    - meta_scope: string.quoted.double.search
    - match: '\\.'
      scope: constant.character.escape.search
    - match: '"'
      scope: punctuation.definition.string.end.search
      pop: true
```
