### ISSUE TITLE
Automatically change appearance with OS (i.e. dark mode support)

### ISSUE THREAD

**Issue by jrappen** [sublimehq/sublime_merge#685]
### Problem description

It would be nice if Sublime Text and Sublime Merge were be able to switch the color scheme when the operating system switches its appearance mode.

### Preferred solution

I wrote a proof of concept plugin for ST4065+:

https://github.com/jrappen/sublime-auto-dark

### References

sublimehq/sublime_text#3236

---

```yaml
Sublime Text:
  build: 4068
  channel: dev
    portable: false
  platform: osx x64

Sublime Merge:
  build: 2000
  channel: dev
    portable: false
  platform: osx x64

System:
  hardware: MBP 15" 2018, i9 2.9GHz, 32GB, 1TB, Radeon Pro 560X
  software: macOS Catalina 10.15.3 (19D76)
    open_gl:
      gl_api_version: 4.1 INTEL-14.4.23
      glsl_version: 4.10
      vendor: Intel Inc.
      renderer: Intel(R) UHD Graphics 630
```
